ifeq '$(pulp_chip)' 'oprecompkw'
IMPLEMENTATIONS += pulp/chips/oprecompkw/job_fifo_impl
COMPONENTS += pulp/chips/oprecompkw/job_fifo
pulp/chips/oprecompkw/job_fifo_impl_SRCS = pulp/chips/oprecompkw/job_fifo_impl.cpp
endif
