ifeq '$(pulp_chip)' 'gap'

IMPLEMENTATIONS += pulp/chips/gap/apb_soc_impl
COMPONENTS += pulp/chips/gap/apb_soc
pulp/chips/gap/apb_soc_impl_SRCS = pulp/chips/gap/apb_soc_impl.cpp

IMPLEMENTATIONS += pulp/chips/gap/rtc_impl
COMPONENTS += pulp/chips/gap/rtc
pulp/chips/gap/rtc_impl_SRCS = pulp/chips/gap/rtc_impl.cpp

endif
