ifeq '$(pulp_chip)' 'oprecompkw_sa'
IMPLEMENTATIONS += pulp/chips/oprecompkw_sa/apb_soc_impl
COMPONENTS += pulp/chips/oprecompkw_sa/apb_soc
pulp/chips/oprecompkw_sa/apb_soc_impl_SRCS = pulp/chips/oprecompkw_sa/apb_soc_impl.cpp
endif
