ifeq '$(event_unit/version)' '3'
IMPLEMENTATIONS += pulp/event_unit/eu_v3_impl
COMPONENTS += pulp/event_unit/eu_v3
pulp/event_unit/eu_v3_impl_SRCS = pulp/event_unit/eu_v3_impl.cpp
endif

ifeq '$(event_unit/version)' 'mempool_v1'
IMPLEMENTATIONS += pulp/event_unit/eu_mempool_v1_impl
COMPONENTS += pulp/event_unit/eu_mempool_v1
pulp/event_unit/eu_mempool_v1_impl_SRCS = pulp/event_unit/eu_mempool_v1_impl.cpp
endif
