ifeq '$(pulp_chip)' 'vivosoc4'

IMPLEMENTATIONS += pulp/chips/vivosoc4/apb_soc_impl
COMPONENTS += pulp/chips/vivosoc4/apb_soc
pulp/chips/vivosoc4/apb_soc_impl_SRCS = pulp/chips/vivosoc4/apb_soc_impl.cpp

#VP_INSTALL_TARGETS += $(INSTALL_DIR)/python/pulp/chips/vivosoc4/rom.bin

#$(INSTALL_DIR)/python/pulp/chips/vivosoc4/rom.bin: $(CURDIR)/pulp/chips/vivosoc4/rom.bin
#	install -D $^ $@

endif
