ifeq '$(pulp_chip)' 'mempool'
IMPLEMENTATIONS += pulp/chips/mempool/apb_soc_impl
COMPONENTS += pulp/chips/mempool/apb_soc
pulp/chips/mempool/apb_soc_impl_SRCS = pulp/chips/mempool/apb_soc_impl.cpp
endif
