ifeq '$(pulp_chip)' 'pulpissimo_v2'
IMPLEMENTATIONS += pulp/chips/pulpissimo_v2/apb_soc_impl
COMPONENTS += pulp/chips/pulpissimo_v2/apb_soc
pulp/chips/pulpissimo_v2/apb_soc_impl_SRCS = pulp/chips/pulpissimo_v2/apb_soc_impl.cpp
endif