ifeq '$(cluster_ctrl/version)' '2'
IMPLEMENTATIONS += pulp/cluster/cluster_ctrl_v2_impl
COMPONENTS += pulp/cluster/cluster_ctrl_v2 pulp/cluster/cluster
pulp/cluster/cluster_ctrl_v2_impl_SRCS = pulp/cluster/cluster_ctrl_v2_impl.cpp
endif