IMPLEMENTATIONS += utils/loader_impl
COMPONENTS += utils/loader utils/composite
utils/loader_impl_SRCS = utils/loader_impl.cpp

IMPLEMENTATIONS += utils/dpi_wrapper_impl
COMPONENTS += utils/dpi_wrapper
utils/dpi_wrapper_impl_SRCS = utils/dpi_wrapper_impl.cpp
utils/dpi_wrapper_impl_LDFLAGS += -lpulpdpi

IMPLEMENTATIONS += utils/injector_impl
COMPONENTS += utils/injector
utils/injector_impl_SRCS = utils/injector_impl.cpp
